name: budget_buddy
description: "A simple budgeting app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.1.0
  plaid_flutter: ^4.2.0
  syncfusion_flutter_charts: ^29.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
